// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvA81veubOAwZXbW0rCByvCu7zHjtT0bo',
    appId: '1:198064451197:android:0f4dbeacc4ffd50a0a4b14',
    messagingSenderId: '198064451197',
    projectId: 'vitta-app-6d44f',
    storageBucket: 'vitta-app-6d44f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkgFTOFXD_2xbko6em6utWeHanCu0lmfM',
    appId: '1:198064451197:ios:5bd81eecd40d58e90a4b14',
    messagingSenderId: '198064451197',
    projectId: 'vitta-app-6d44f',
    storageBucket: 'vitta-app-6d44f.firebasestorage.app',
    iosBundleId: 'com.example.vittaApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjD4zYIXClfbyc2E7uGD8aB_1i7P3sQmU',
    appId: '1:198064451197:web:8b43864c40f572ed0a4b14',
    messagingSenderId: '198064451197',
    projectId: 'vitta-app-6d44f',
    authDomain: 'vitta-app-6d44f.firebaseapp.com',
    storageBucket: 'vitta-app-6d44f.firebasestorage.app',
  );

}